export const FOYER = "THE GRAND FOYER"
export const STAIRCASE = "THE GRAND STAIRCASE"
export const GALLERY = "THE GALLERY"
export const STAGE = "THE STAGE"
export const MUSIC_HALL = "THE MUSIC HALL"
export const DANCE_HALL = "THE DANCE HALL"

export const LOCATIONS = [
	DANCE_HALL,
	MUSIC_HALL,
	STAGE,
	GALLERY,
	STAIRCASE,
	FOYER
]

export const MAP = {
	[FOYER]: [STAIRCASE, GALLERY],
	[STAIRCASE]: [FOYER, GALLERY],
	[GALLERY]: [FOYER, STAIRCASE, STAGE],
	[STAGE]: [GALLERY, MUSIC_HALL, DANCE_HALL],
	[MUSIC_HALL]: [STAGE, DANCE_HALL],
	[DANCE_HALL]: [STAGE, MUSIC_HALL]
}